name: Generate Video

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        run: node generate_quiz.js

      - name: Upload Quiz Image
        uses: actions/upload-artifact@v4
        with:
          name: quiz-image
          path: quiz.png
          
