name: Generate Video from HTML

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg xserver-xorg xvfb libnss3 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libappindicator3-1 libasound2 

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Capture Video
        run: |
          Xvfb :99 -screen 0 1280x720x24 & 
          export DISPLAY=:99
          node capture.js --no-sandbox --disable-setuid-sandbox --headless=new

      - name: Upload Video
        uses: actions/upload-artifact@v4
        with:
          name: quiz-video
          path: output.mp4
