name: Generate Video from HTML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting the video generation job..."

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Install Node.js and Puppeteer
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM Packages
        run: |
          npm cache clean --force
          rm -f package-lock.json
          npm install --legacy-peer-deps

      - name: Install Puppeteer Manually
        run: npm install puppeteer --unsafe-perm=true --allow-root

      - name: Capture Video
        run: |
          Xvfb :99 -screen 0 1280x720x24 &
          export DISPLAY=:99
          node generate-video.js  # ⚠️ अपना सही स्क्रिप्ट नाम चेक करें!

      - name: Upload Video
        uses: actions/upload-artifact@v4
        with:
          name: generated-video
          path: output.mp4  # ⚠️ यहां अपना सही आउटपुट वीडियो पाथ डालें!

      - name: Complete job
        run: echo "Video generation completed successfully!"
        
