name: Generate Video from HTML

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg xvfb libnss3 libatk1.0-0 libx11-xcb1 \
          libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxrandr2 \
          libgbm1 libglib2.0-0 libnss3 libpango-1.0-0 libatk-bridge2.0-0 \
          libxss1 libgtk-3-0 fonts-liberation libasound2 libdrm2 \
          libxcb-dri3-0 libxshmfence1 libx11-xcb1 libxtst6 \
          --no-install-recommends

      - name: Install Node.js and Puppeteer
        run: |
          export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
          npm install puppeteer

      - name: Capture Video
        run: |
          Xvfb :99 -screen 0 1280x720x24 &
          export DISPLAY=:99
          node capture.js --no-sandbox --disable-setuid-sandbox

      - name: Upload Video
        uses: actions/upload-artifact@v4
        with:
          name: quiz-video
          path: output.mp4
          
