name: Video Generation Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        run: node index.js

      - name: Convert Image to 10-Second Video
        run: ffmpeg -loop 1 -i quiz.png -c:v libx264 -t 10 -pix_fmt yuv420p output.mp4

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-video
          path: output.mp4
          
