name: Generate Video from HTML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting video generation job..."

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb ffmpeg

      - name: Install Node.js and Puppeteer
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM Packages
        run: npm install

      - name: Capture Video
        run: |
          export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
          export PUPPETEER_EXECUTABLE_PATH=$(which google-chrome-stable)
          Xvfb :99 -screen 0 1280x720x24 &
          npm run capture -- --no-sandbox --disable-setuid-sandbox

      - name: Upload Video
        uses: actions/upload-artifact@v4
        with:
          name: generated-video
          path: output/video.mp4

      - name: Complete job
        run: echo "Video generation completed successfully!"
        
